// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCu5hxn0DJpqx_MmfNjwaiYYgECwz0YEu0',
//     appId: '1:971833702888:web:1b160add3e2c4849b58c5d',
//     messagingSenderId: '971833702888',
//     projectId: 'smart-shop-e1782',
//     authDomain: 'smart-shop-e1782.firebaseapp.com',
//     storageBucket: 'smart-shop-e1782.appspot.com',
//     measurementId: 'G-MLH1QW2TFY',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAO1qXRoLMR46PpT_Lu6P4JlAn_dpTYrPc',
//     appId: '1:971833702888:android:30b86114770e2495b58c5d',
//     messagingSenderId: '971833702888',
//     projectId: 'smart-shop-e1782',
//     storageBucket: 'smart-shop-e1782.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAw74wO1YUU_RLDUgHJof8sYILzHiWjYQ4',
//     appId: '1:971833702888:ios:f4b464d673c643a0b58c5d',
//     messagingSenderId: '971833702888',
//     projectId: 'smart-shop-e1782',
//     storageBucket: 'smart-shop-e1782.appspot.com',
//     iosBundleId: 'com.example.adminSmartShop',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAw74wO1YUU_RLDUgHJof8sYILzHiWjYQ4',
//     appId: '1:971833702888:ios:847b43967a2a1d81b58c5d',
//     messagingSenderId: '971833702888',
//     projectId: 'smart-shop-e1782',
//     storageBucket: 'smart-shop-e1782.appspot.com',
//     iosBundleId: 'com.example.adminSmartShop.RunnerTests',
//   );
// }
